version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sarah-clements
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: taskcluster
    versions:
    - 41.1.0
    - 42.1.0
    - 42.1.1
    - 43.0.0
  - dependency-name: django-extensions
    versions:
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: pip-tools
    versions:
    - 5.5.0
    - 6.0.0
    - 6.0.1
  - dependency-name: json-e
    versions:
    - 4.3.0
    - 4.4.0
  - dependency-name: django
    versions:
    - 3.1.7
